apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: realms.keycloak.kubed.io
spec:
  scope: Cluster
  group: keycloak.kubed.io
  names:
    kind: Realm
    plural: realms
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              displayName:
                description: The display name of the realm.
                type: string
              displayNameHtml:
                description: The display name HTML of the realm.
                type: string
              enabled:
                description: When false, users and clients will not be able to access this realm. Defaults to true.
                type: boolean
                default: true
          status:
            description: A Status represents the observed state
            type: object
            properties:
              share:
                description: Freeform field containing status information
                type: object
                x-kubernetes-preserve-unknown-fields: true
